services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: grpc-client
    networks:
      benchnet:
        ipv4_address: 172.30.0.3
    volumes:
      - ./logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    stdin_open: true
    privileged: true
    depends_on:
      - router
      - server
    command: ["/usr/local/bin/sync_time.sh", "sleep", "infinity"]

  router:
    build:
      context: .
      dockerfile: router/Dockerfile
    container_name: grpc-router
    networks:
      benchnet:
        ipv4_address: 172.30.0.254
    cap_add:
      - NET_ADMIN
    privileged: true
    command: ["/usr/local/bin/sync_time.sh", "sleep", "infinity"]

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: grpc-server
    networks:
      benchnet:
        ipv4_address: 172.30.0.2
    ports:
      - "80:80"   # HTTP/2
      - "443:443" # HTTPS/HTTP/3
    privileged: true
    command: ["/usr/local/bin/sync_time.sh", "/opt/nginx-h3/sbin/nginx", "-g", "daemon off;"]

networks:
  benchnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24 